name: Keep Render Alive

on:
  schedule:
    - cron: '*/30 * * * *' # cada 30 minutos
  workflow_dispatch:      # permite ejecutar manualmente

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: |
          echo "Haciendo ping a tu servicio..."
          curl -s --connect-timeout 10 https://r2-n8n.onrender.com